### ISSUE TITLE
Name of your repository on Udemy

### ISSUE THREAD

**Issue by benoitLebreton-perso** [CodeWithPraveen/labs-docker-privateregistry#1]
Hello thank you for this lab

I got here thanks to Udemy

<img width="672" alt="image" src="https://user-images.githubusercontent.com/51739671/202289889-119422c5-6832-4757-8779-c0954373d96a.png">

Can you update the name of your repositroy in the Udemy instruction `CodeWithPraveen/labs-docker-privateregistry` instead of `BrezyWeather`

**Comment by CodeWithPraveen** [comment]
Hi, I mentioned BrezyWeather, as that is the project in the repo. The name **CodeWithPraveen/labs-docker-privateregistry** is more to uniquely distinguish the repo from others.
