### ISSUE TITLE
Region of the App Service

### ISSUE THREAD

**Issue by benoitLebreton-perso** [CodeWithPraveen/labs-docker-privateregistry#3]
Hello 

Still on the Udemy lab

<img width="696" alt="image" src="https://user-images.githubusercontent.com/51739671/202295473-67075656-7321-410d-8d83-04cd3c17ee36.png">

I think you should explicitly write to choose the `West US` region at this step

**Comment by CodeWithPraveen** [comment]
Hi, That detail is included in the How-To steps for that task.
