### ISSUE TITLE
[Feature Request] Your CICD should go until the deployment to App Service

### ISSUE THREAD

**Issue by benoitLebreton-perso** [CodeWithPraveen/labs-docker-privateregistry#4]
Your github actions CICD stop at the push to the container registry.

It would be so better if you add a step "Deployment to the App Service" at the end.

You could have two steps with :  
- connection to the azure subscription `az login ....`
- (Optionnal) get the ressource group name if needed ?)
- use the `az` CLI to deploy the App Service using the new docker image : `az functionapp config container set --docker-custom-image-name $ACR_SITE:$docker_image --docker-registry-server-password $ACR_PASSWORD --docker-registry-server-url $docker_registry_url --docker-registry-server-user $ACR_USERNAME --name $functionapp_name --resource-group $RESSOURCE_GROUP_NAME`

and the tag would be the same as the github tag (instead of just hard coding the 1.0.0)

**Comment by CodeWithPraveen** [comment]
Hi there, 

Thanks for sharing your comments. The steps were kept simple as it was targeting beginners. It is possible to use Azure CLI to manage it better with more controls. However, it will then be outside the scope of this lab. 

I have taken note of your feedback. I will review it when I do a related lab on this topic. 

Thank you, 
Praveen
